(function(){'use strict';
const E=(s)=>String(s||'').toLowerCase();
const specs=[
{re:/largest.*element.*array|largest element/i,pattern:'Linear scan',brief:'Given an array, return its largest value.',input:'First line n, second line n integers.',output:'Print the largest integer.',time:'O(n)',space:'O(1)',tests:[['Basic','5\n2 5 1 8 3','8'],['Negative','4\n-9 -2 -7 -4','-2'],['Single','1\n42','42']]},
{re:/second.*largest/i,pattern:'Two best values',brief:'Find the second distinct largest value in an array.',input:'First line n, second line n integers.',output:'Print the second distinct largest value.',time:'O(n)',space:'O(1)',tests:[['Basic','5\n1 2 4 7 7','4'],['Negative','4\n-5 -1 -3 -2','-2']]},
{re:/sorted.*rotated|check.*sorted/i,pattern:'Single pass',brief:'Determine whether the array satisfies the requested sorted-order property.',input:'First line n, second line n integers.',output:'Print true/false or 1/0 according to your implementation contract.',time:'O(n)',space:'O(1)'},
{re:/remove duplicates.*sorted/i,pattern:'Two pointers',brief:'Remove duplicates from a sorted array in-place and report the resulting logical length or sequence.',input:'First line n, second line sorted integers.',output:'Print the requested resulting length/sequence.',time:'O(n)',space:'O(1)'},
{re:/move.*zero/i,pattern:'Two pointers',brief:'Move all zeroes to the end while preserving the relative order of non-zero values.',input:'First line n, second line n integers.',output:'Print the transformed array.',time:'O(n)',space:'O(1)',tests:[['Basic','5\n0 1 0 3 12','1 3 12 0 0'],['No zero','3\n1 2 3','1 2 3']]},
{re:/linear search/i,pattern:'Linear scan',brief:'Find the target in the array.',input:'n, array, then target.',output:'Print the target index or the problem-defined not-found value.',time:'O(n)',space:'O(1)'},
{re:/missing number/i,pattern:'XOR or arithmetic invariant',brief:'Find the single missing value from the expected integer range.',input:'n and the present values.',output:'Print the missing value.',time:'O(n)',space:'O(1)',tests:[['Basic','5\n0 1 3 4 5','2'],['Zero missing','3\n1 2 3','0']]},
{re:/max.*consecutive.*1|maximum consecutive ones/i,pattern:'Running count',brief:'Return the longest contiguous run of ones.',input:'n then a binary array.',output:'Print the maximum run length.',time:'O(n)',space:'O(1)',tests:[['Basic','6\n1 1 0 1 1 1','3'],['None','4\n0 0 0 0','0']]},
{re:/two sum|2 sum/i,pattern:'Hash lookup',brief:'Find two values whose sum equals the target.',input:'n, array, then target.',output:'Print the requested pair/indices.',time:'O(n)',space:'O(n)'},
{re:/sort.*0.*1.*2|dutch/i,pattern:'Dutch National Flag',brief:'Sort an array containing only 0, 1, and 2 without general-purpose sorting.',input:'n then the array.',output:'Print the sorted array.',time:'O(n)',space:'O(1)',tests:[['Mixed','6\n2 0 2 1 1 0','0 0 1 1 2 2']]},
{re:/majority element/i,pattern:'Boyer-Moore voting',brief:'Find the element occurring more than half the time when such an element is guaranteed.',input:'n then array.',output:'Print the majority element.',time:'O(n)',space:'O(1)'},
{re:/kadane|maximum subarray/i,pattern:'Kadane dynamic invariant',brief:'Find the maximum sum over all contiguous subarrays.',input:'n then array.',output:'Print the maximum subarray sum.',time:'O(n)',space:'O(1)',tests:[['Classic','9\n-2 1 -3 4 -1 2 1 -5 4','6'],['All negative','3\n-8 -2 -5','-2']]},
{re:/stock.*buy.*sell|best time.*stock/i,pattern:'Prefix minimum',brief:'Maximize profit from the allowed stock transaction model.',input:'n then prices.',output:'Print maximum profit.',time:'O(n)',space:'O(1)'},
{re:/longest consecutive/i,pattern:'Hash set starts',brief:'Find the length of the longest consecutive-value sequence.',input:'n then unsorted integers.',output:'Print the longest length.',time:'O(n)',space:'O(n)'},
{re:/binary search(?! tree)|search in sorted/i,pattern:'Binary search',brief:'Find a target in sorted search space by repeatedly discarding half.',input:'n, sorted array, target.',output:'Print the requested index/not-found value.',time:'O(log n)',space:'O(1)',tests:[['Found','6\n1 3 5 7 9 11\n7','3'],['Missing','4\n2 4 6 8\n5','-1']]},
{re:/lower bound/i,pattern:'Binary search boundary',brief:'Find the first position satisfying the lower-bound predicate.',input:'n, sorted array, target.',output:'Print the boundary index.',time:'O(log n)',space:'O(1)'},
{re:/upper bound/i,pattern:'Binary search boundary',brief:'Find the first position strictly beyond the target value.',input:'n, sorted array, target.',output:'Print the boundary index.',time:'O(log n)',space:'O(1)'},
{re:/square root|sqrt/i,pattern:'Binary search on answer',brief:'Compute the requested integer/precision square root without scanning every candidate.',input:'An integer/value.',output:'Print the requested root.',time:'O(log n)',space:'O(1)'},
{re:/balanced parenth|valid parenth/i,pattern:'Stack',brief:'Check whether bracket ordering is valid.',input:'A bracket string.',output:'Print true/false.',time:'O(n)',space:'O(n)',tests:[['Valid','()[]{}','true'],['Invalid','([)]','false']]},
{re:/longest substring.*without repeating/i,pattern:'Sliding window',brief:'Find the longest substring containing no repeated character.',input:'A string.',output:'Print the maximum length.',time:'O(n)',space:'O(k)',tests:[['Classic','abcabcbb','3'],['Repeated','bbbbb','1']]},
{re:/kth.*largest|kth.*smallest/i,pattern:'Heap / selection',brief:'Find the kth ranked value efficiently.',input:'n, values, k.',output:'Print the kth requested value.',time:'O(n log k)',space:'O(k)'},
{re:/climbing stairs/i,pattern:'1D DP',brief:'Count the ways to reach the top under the allowed step sizes.',input:'n.',output:'Print the number of ways.',time:'O(n)',space:'O(1)',tests:[['Two','2','2'],['Five','5','8']]},
{re:/house robber/i,pattern:'Take / skip DP',brief:'Maximize the sum while respecting the non-adjacency constraint.',input:'n then values.',output:'Print the maximum obtainable sum.',time:'O(n)',space:'O(1)'},
{re:/unique paths/i,pattern:'Grid DP',brief:'Count valid paths through the grid under the stated movement rules.',input:'Grid dimensions.',output:'Print path count.',time:'O(mn)',space:'O(n)'},
{re:/longest common subsequence|\blcs\b/i,pattern:'2D DP',brief:'Find the length/value of a longest common subsequence.',input:'Two sequences/strings.',output:'Print the requested LCS result.',time:'O(mn)',space:'O(mn)'},
{re:/edit distance/i,pattern:'2D DP',brief:'Find the minimum edit operations needed to transform one string into another.',input:'Two strings.',output:'Print minimum edit distance.',time:'O(mn)',space:'O(mn)'},
{re:/longest increasing subsequence|\blis\b/i,pattern:'DP / patience sorting',brief:'Find the length of a longest strictly increasing subsequence.',input:'n then values.',output:'Print the LIS length.',time:'O(n log n)',space:'O(n)'}
];
function choose(p){return specs.find(s=>s.re.test(p.title||''))||null}
function tags(p,s){const t=[];if(s?.pattern)t.push(s.pattern);const x=E(p.topic);if(x.includes('array'))t.push('Array');else if(x.includes('graph'))t.push('Graph');else if(x.includes('tree'))t.push('Tree');else if(x.includes('dynamic'))t.push('DP');else if(x.includes('string'))t.push('String');else if(x.includes('linked'))t.push('Linked List');else if(x.includes('heap'))t.push('Heap');return [...new Set(t)].slice(0,3)}
function starter(p,lang){const title=(p?.title||'Problem').replace(/\*\//g,'');if(lang==='python')return `# ${title}\n# Read stdin, solve the problem, print the answer.\n\ndef solve():\n    # TODO: parse input\n    pass\n\nif __name__ == "__main__":\n    solve()\n`;if(lang==='javascript')return `// ${title}\nconst input = __INPUT__.trim();\n\nfunction solve(input) {\n  // TODO\n}\n\nconst ans = solve(input);\nif (ans !== undefined) console.log(ans);\n`;if(lang==='cpp')return `#include <bits/stdc++.h>\nusing namespace std;\n\nint main(){\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n    // ${title}\n    // TODO\n    return 0;\n}\n`;return `import java.io.*;\nimport java.util.*;\n\npublic class Main {\n  public static void main(String[] args) throws Exception {\n    // ${title}\n    // TODO\n  }\n}\n`}
function enrich(p){const s=choose(p);const pattern=s?.pattern||inferPattern(p);const time=s?.time||inferTime(pattern);const space=s?.space||inferSpace(pattern);const hints=[`Restate the input/output contract and write down the smallest useful invariant for ${pattern.toLowerCase()}.`,`Before coding, identify the brute-force search space and what repeated work can be removed.`,`Aim for ${time} time${space?` and ${space} auxiliary space`:''}; test empty/minimum, duplicate, monotonic, and extreme-value cases.`];const tests=(s?.tests||[]).map((x,i)=>({name:x[0],stdin:x[1],expected:x[2],hidden:i>0}));return {...p,brief:s?.brief||`Practice “${p.title}” as an interview problem. Use the canonical source for exact constraints, then derive your own solution before opening hints.`,inputFormat:s?.input||'Use the canonical source contract. For local execution, provide equivalent stdin.',outputFormat:s?.output||'Print the result required by the canonical problem.',tags:tags(p,s),hints,tests,validationCoverage:tests.length?'curated':'custom',guide:{pattern,targetTime:time,targetSpace:space,interviewSteps:[`Clarify constraints and examples before choosing ${pattern}.`,'State the invariant/state definition out loud.','Walk one edge case by hand before writing code.','Implement, then test the smallest input, duplicate-heavy input, and a worst-shaped input.','Explain why the complexity follows from the number of states/iterations and data-structure operations.'],commonMistakes:['Coding before locking down the input/output contract.','Handling the happy path but missing duplicates, boundaries, or empty/minimum input.','Quoting Big-O without counting nested work or auxiliary structure growth.'],followUps:['Can you reduce auxiliary memory?','What changes if the input is streamed or too large for memory?','Which invariant would you explain first in a real interview?']}}
}
function inferPattern(p){const t=E(`${p.title} ${p.topic}`);if(t.includes('graph'))return 'Graph traversal / shortest-path pattern';if(t.includes('tree'))return 'Tree traversal / recursion';if(t.includes('dynamic'))return 'Dynamic programming';if(t.includes('sliding'))return 'Sliding window / two pointers';if(t.includes('heap'))return 'Heap / priority queue';if(t.includes('greedy'))return 'Greedy invariant';if(t.includes('bit'))return 'Bit manipulation';if(t.includes('recursion'))return 'Recursion / backtracking';if(t.includes('linked'))return 'Pointer manipulation';if(t.includes('binary search'))return 'Binary search';if(t.includes('string'))return 'String scan / hashing';return 'Array / data-structure reasoning'}
function inferTime(p){if(/binary search/i.test(p))return'O(log n)';if(/dynamic|graph|tree|recursion|backtracking/i.test(p))return'problem dependent';if(/heap/i.test(p))return'O(n log k)';return'O(n) or better'}
function inferSpace(p){if(/tree|graph|dynamic|hash|heap|recursion|backtracking/i.test(p))return'problem dependent';return'O(1) to O(n)'}
window.ProblemEngine={enrich,starter};
})();
